# Generated by Django 4.0.4 on 2022-05-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_rename_id_todolog_unique_id_remove_todoitem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolog',
            name='tag',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
