# Generated by Django 4.0.4 on 2022-05-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_todolog_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='tag',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
