# Generated by Django 4.0.4 on 2022-05-17 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='tag_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='todo.tag'),
        ),
        migrations.AddField(
            model_name='todolog',
            name='tag_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='todo.tag'),
        ),
    ]
