# Generated by Django 4.0.4 on 2022-05-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_todoitem_tag_ref_todolog_tag_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='tag_ref',
        ),
        migrations.RemoveField(
            model_name='todolog',
            name='tag_ref',
        ),
    ]
