# Generated by Django 4.0.4 on 2022-05-18 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_todoitem_tag_ref_todolog_tag_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='tag_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='todo.tag'),
        ),
        migrations.AlterField(
            model_name='todolog',
            name='tag_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='todo.tag'),
        ),
    ]
