# Generated by Django 4.0.4 on 2022-05-18 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_remove_todoitem_tag_ref_remove_todolog_tag_ref'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
