# Generated by Django 4.0.4 on 2022-05-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_delete_tag'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='todolog',
            index=models.Index(fields=['completion', 'date'], name='todo_todolo_complet_dd8b28_idx'),
        ),
    ]
