# Generated by Django 4.0.4 on 2022-05-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0018_todolog_todo_todolo_complet_dd8b28_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='todolog',
            index=models.Index(fields=['date'], name='todo_todolo_date_8d8d59_idx'),
        ),
    ]
