# Generated by Django 4.0.4 on 2022-05-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_todolog_todo_todolo_date_8d8d59_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='todolog',
            index=models.Index(fields=['tag'], name='todo_todolo_tag_3deafb_idx'),
        ),
    ]
