# Generated by Django 4.0.4 on 2022-05-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0020_todolog_todo_todolo_tag_3deafb_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='todolog',
            name='todo_todolo_complet_dd8b28_idx',
        ),
        migrations.RemoveIndex(
            model_name='todolog',
            name='todo_todolo_date_8d8d59_idx',
        ),
        migrations.AddIndex(
            model_name='todolog',
            index=models.Index(fields=['date', 'completion'], name='todo_todolo_date_3dd119_idx'),
        ),
        migrations.AddIndex(
            model_name='todolog',
            index=models.Index(fields=['completion'], name='todo_todolo_complet_d33c66_idx'),
        ),
    ]
