# Generated by Django 4.0.4 on 2022-05-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0021_remove_todolog_todo_todolo_complet_dd8b28_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='todolog',
            index=models.Index(fields=['date', 'tag', 'completion'], name='todo_todolo_date_478d97_idx'),
        ),
    ]
