# Generated by Django 4.0.4 on 2022-05-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0022_todolog_todo_todolo_date_478d97_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='todolog',
            name='todo_todolo_date_478d97_idx',
        ),
        migrations.AddIndex(
            model_name='todolog',
            index=models.Index(fields=['date', 'duration', 'unique_id'], name='todo_todolo_date_202e91_idx'),
        ),
    ]
