# Generated by Django 4.0.4 on 2022-05-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0025_activetimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='activetimer',
            name='paused',
            field=models.DateTimeField(null=True),
        ),
    ]
