# Generated by Django 4.0.4 on 2022-05-20 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0026_activetimer_paused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activetimer',
            name='linked_todo_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='todo.todolog'),
        ),
    ]
