# Generated by Django 4.0.4 on 2022-05-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0027_alter_activetimer_linked_todo_log'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activetimer',
            index=models.Index(fields=['linked_todo_log'], name='todo_active_linked__e8c24c_idx'),
        ),
    ]
