# Generated by Django 4.0.4 on 2022-05-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0028_activetimer_todo_active_linked__e8c24c_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stats', models.JSONField()),
            ],
        ),
        migrations.AddIndex(
            model_name='stats',
            index=models.Index(fields=['date'], name='todo_stats_date_0bf242_idx'),
        ),
    ]
