# Generated by Django 4.0.4 on 2022-05-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0029_stats_stats_todo_stats_date_0bf242_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stats',
            name='todo_stats_date_0bf242_idx',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='id',
        ),
        migrations.AlterField(
            model_name='stats',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
