# Generated by Django 4.0.4 on 2022-05-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0032_remove_activetimer_todo_active_linked__e8c24c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stats',
            name='todo_stats_user_id_7dec26_idx',
        ),
        migrations.AddIndex(
            model_name='stats',
            index=models.Index(fields=['date', 'user_id'], name='todo_stats_date_abd46d_idx'),
        ),
    ]
