# Generated by Django 4.0.4 on 2022-06-02 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0033_remove_stats_todo_stats_user_id_7dec26_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activetimer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
