# Generated by Django 4.0.4 on 2022-06-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0035_alter_activetimer_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activetimer',
            index=models.Index(fields=['user_id'], name='todo_active_user_id_010579_idx'),
        ),
    ]
