# Generated by Django 4.0.4 on 2022-06-05 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0036_activetimer_todo_active_user_id_010579_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activetimer',
            name='todo_active_user_id_010579_idx',
        ),
    ]
