# Generated by Django 4.0.4 on 2023-05-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0037_remove_activetimer_todo_active_user_id_010579_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='streak',
            field=models.IntegerField(null=True),
        ),
    ]
