# Generated by Django 4.0.4 on 2022-05-14 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_todoitem_todolog_alter_greeting_when'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
