# Generated by Django 4.0.4 on 2022-05-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_remove_todoitem_name_remove_todolog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolog',
            name='completion',
            field=models.BooleanField(default=False),
        ),
    ]
